version: "3.7"

services:

    move-rows-to-shards:
        image: gcr.io/mcback/move-rows-to-shards:latest
        init: true
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/move-rows-to-shards/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - temporal-server

            # Not needed for running the test but useful for debugging, demos
            # and such
            # - temporal-webapp

    postgresql-pgbouncer:
        image: gcr.io/mcback/postgresql-pgbouncer:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 6432
        volumes:
            - type: bind
              source: ./../postgresql-pgbouncer/conf/
              target: /etc/pgbouncer/
        depends_on:
            - postgresql-server

    postgresql-server:
        image: gcr.io/mcback/postgresql-server:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../postgresql-server/bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./../postgresql-server/pgmigrate/
              target: /opt/postgresql-server/pgmigrate/
            - type: bind
              source: ./../postgresql-server/etc/postgresql/14/extra/
              target: /etc/postgresql/14/extra/
            - type: bind
              source: ./../postgresql-base/etc/postgresql/14/main/
              target: /etc/postgresql/14/main/

    temporal-server:
        image: gcr.io/mcback/temporal-server:latest
        init: true
        stop_signal: SIGKILL
        depends_on:
            - temporal-postgresql
            - temporal-elasticsearch
        expose:
            - 6933
            - 6934
            - 6935
            - 6939
            - 7233
            - 7234
            - 7235
            - 7239
        volumes:
            - type: bind
              source: ./../temporal-server/bin/
              target: /opt/temporal-server/bin/
            - type: bind
              source: ./../temporal-server/config/dynamicconfig.yaml
              target: /opt/temporal-server/config/dynamicconfig.yaml
            - type: bind
              source: ./../temporal-server/config/mediacloud_template.yaml
              target: /opt/temporal-server/config/mediacloud_template.yaml

    temporal-postgresql:
        image: gcr.io/mcback/temporal-postgresql:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - 5432
        volumes:
            - type: bind
              source: ./../temporal-postgresql/bin/
              target: /opt/temporal-postgresql/bin/
            - type: bind
              source: ./../postgresql-base/etc/postgresql/14/main/
              target: /etc/postgresql/14/main/

    temporal-elasticsearch:
        image: gcr.io/mcback/temporal-elasticsearch:latest
        init: true
        stop_signal: SIGKILL
        expose:
            - "9200"
            - "9300"
        volumes:
            - type: bind
              source: ./../elasticsearch-base/bin/elasticsearch.sh
              target: /opt/elasticsearch/bin/elasticsearch.sh
            # Not mounting config as it gets concatenated into a single file
        # Limit CPUs and RAM for the process to not get too greedy
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2G"

    # temporal-webapp:
    #     image: gcr.io/mcback/temporal-webapp:latest
    #     init: true
    #     stop_signal: SIGKILL
    #     expose:
    #         - "8088"
    #     ports:
    #         # Expose to host for debugging
    #         - "8088:8088"
